# Calculating OPS+

The formula for OPS+ is:
```
    OPS/lgOPS * 100
```
However the problem is making the formula iterable across rows. I'm not sure about how to write a lambda, or function, that makes sure that Player A's OPS is divided by the lgOPS of that year.

In [1]:
import advanced_statlines as stat 
import pandas as pd 
import numpy as np 
import mysql.connector as sql
from IPython import display

pd.options.display.max_columns = None

In [2]:
batting = pd.read_csv('multiyear_batting_example.csv')
stat.format_df(batting)
batting = batting[batting.PA > 350]
batting = stat.order_by(batting, 'OPS', False)
batting.head()

,ID,playerID,yearID,stint,teamID,team_ID,lgID,G,G_batting,AB,R,H,2B,3B,HR,RBI,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP,PA,OBP,AVG,SLG,OPS
0,107416,yelicch01,2019,1,MIL,2911,NL,130,NaN,489,100,161,29,3,44,97,30,2,80,118,16,8,0,3,8,580,0.429310,0.329243,0.670757,1.100067
1,105724,troutmi01,2018,1,LAA,2878,AL,140,NaN,471,101,147,24,4,39,79,24,2,122,124,25,10,0,4,5,607,0.459638,0.312102,0.628450,1.088088
2,107288,troutmi01,2019,1,LAA,2908,AL,134,NaN,470,110,137,27,2,45,104,11,2,110,120,14,16,0,4,5,600,0.438333,0.291489,0.644681,1.083014
3,104454,bettsmo01,2018,1,BOS,2869,AL,136,NaN,520,129,180,47,5,32,80,30,6,81,91,8,8,0,5,5,614,0.438111,0.346154,0.640385,1.078495
4,105912,alvaryo01,2019,1,HOU,2906,AL,87,NaN,313,58,98,26,0,27,78,0,0,52,94,4,2,0,2,9,369,0.411924,0.313099,0.654952,1.066876

In [11]:
test_df = batting[(batting.playerID == 'troutmi01') & 
                    (batting.yearID == 2018)]
lgOPS = batting.groupby('yearID').OPS.mean().reset_index()
test_df

,ID,playerID,yearID,stint,teamID,team_ID,lgID,G,G_batting,AB,R,H,2B,3B,HR,RBI,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP,PA,OBP,AVG,SLG,OPS
1,105724,troutmi01,2018,1,LAA,2878,AL,140,NaN,471,101,147,24,4,39,79,24,2,122,124,25,10,0,4,5,607,0.459638,0.312102,0.62845,1.088088

In [12]:
print(lgOPS)

   yearID       OPS
0    2018  0.763437
1    2019  0.795498

ValueError: Can only compare identically-labeled Series objects