In [1]:
import mysql.connector as sql
import pandas as pd 
import numpy as np 
import advanced_statlines as stat

In [5]:
pd.options.display.max_columns = None

In [6]:
batting = pd.read_csv('ari2001_batting.csv')
batting.head()

,playerID,nameFirst,nameLast,ID,playerID.1,yearID,stint,teamID,team_ID,lgID,G,G_batting,AB,R,H,2B,3B,HR,RBI,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP
0,anderbr02,Brian,Anderson,80676,anderbr02,2001,1,ARI,2357,NL,33,NaN,37,1,5,1,1,0,2,0,0,0,9,0,0,0,0,2
1,barajro01,Rod,Barajas,80708,barajro01,2001,1,ARI,2357,NL,51,NaN,106,9,17,3,0,3,9,0,0,4,26,0,0,0,0,0
2,batismi01,Miguel,Batista,80716,batismi01,2001,1,ARI,2357,NL,48,NaN,32,2,2,0,0,0,0,0,0,2,17,0,0,2,0,0
3,bautida01,Danny,Bautista,80720,bautida01,2001,1,ARI,2357,NL,100,NaN,222,26,67,11,2,5,26,3,2,14,31,1,1,2,0,7
4,bellja01,Jay,Bell,80731,bellja01,2001,1,ARI,2357,NL,129,NaN,428,59,106,24,1,13,46,0,1,65,79,3,4,8,4,9

In [7]:
display(stat.order_by(batting, 'AB', False).head())

,playerID,nameFirst,nameLast,ID,playerID.1,yearID,stint,teamID,team_ID,lgID,G,G_batting,AB,R,H,2B,3B,HR,RBI,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP
0,gonzalu01,Luis,Gonzalez,81096,gonzalu01,2001,1,ARI,2357,NL,162,NaN,609,128,198,36,7,57,142,1,1,100,83,24,14,0,5,14
1,finlest01,Steve,Finley,81027,finlest01,2001,1,ARI,2357,NL,140,NaN,495,66,136,27,4,14,73,11,7,47,67,9,1,2,3,8
2,womacto01,Tony,Womack,81966,womacto01,2001,1,ARI,2357,NL,125,NaN,481,66,128,19,5,3,30,28,7,23,54,2,6,7,1,4
3,gracema01,Mark,Grace,81101,gracema01,2001,1,ARI,2357,NL,145,NaN,476,66,142,31,2,15,78,1,0,67,36,6,4,1,5,7
4,counscr01,Craig,Counsell,80901,counscr01,2001,1,ARI,2357,NL,141,NaN,458,76,126,22,3,4,38,6,8,61,76,3,2,6,6,9